# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testblogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='append_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
