# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 22:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testblogapp', '0005_auto_20161202_1553'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='viewed',
            unique_together=set([('user', 'post')]),
        ),
    ]
